export type Airport = {
	code: string;
	name: string;
	city: string;
	country: string;
	lat: number;
	lon: number;
};

export const airports: Airport[] = [
	// Hong Kong SAR
	{
		code: "HKG",
		name: "Hong Kong Intl",
		city: "Hong Kong",
		country: "Hong Kong",
		lat: 22.308,
		lon: 113.9185,
	},

	// Chinese Mainland
	{
		code: "PEK",
		name: "Beijing Capital",
		city: "Beijing",
		country: "China",
		lat: 40.0801,
		lon: 116.5846,
	},
	{
		code: "PKX",
		name: "Beijing Daxing",
		city: "Beijing",
		country: "China",
		lat: 39.5099,
		lon: 116.4108,
	},
	{
		code: "CTU",
		name: "Chengdu Tianfu",
		city: "Chengdu",
		country: "China",
		lat: 30.314,
		lon: 104.441,
	},
	{
		code: "CKG",
		name: "Chongqing Jiangbei",
		city: "Chongqing",
		country: "China",
		lat: 29.7192,
		lon: 106.6417,
	},
	{
		code: "FOC",
		name: "Fuzhou Changle",
		city: "Fuzhou",
		country: "China",
		lat: 25.9342,
		lon: 119.6633,
	},
	{
		code: "CAN",
		name: "Guangzhou Baiyun",
		city: "Guangzhou",
		country: "China",
		lat: 23.3924,
		lon: 113.2988,
	},
	{
		code: "HAK",
		name: "Haikou Meilan",
		city: "Haikou",
		country: "China",
		lat: 19.9349,
		lon: 110.458,
	},
	{
		code: "HGH",
		name: "Hangzhou Xiaoshan",
		city: "Hangzhou",
		country: "China",
		lat: 30.2295,
		lon: 120.4345,
	},
	{
		code: "NKG",
		name: "Nanjing Lukou",
		city: "Nanjing",
		country: "China",
		lat: 31.742,
		lon: 118.861,
	},
	{
		code: "NGB",
		name: "Ningbo Lishe",
		city: "Ningbo",
		country: "China",
		lat: 29.8267,
		lon: 121.4619,
	},
	{
		code: "TAO",
		name: "Qingdao Jiaodong",
		city: "Qingdao",
		country: "China",
		lat: 36.265,
		lon: 120.374,
	},
	{
		code: "PVG",
		name: "Shanghai Pudong",
		city: "Shanghai",
		country: "China",
		lat: 31.1443,
		lon: 121.8083,
	},
	{
		code: "SHA",
		name: "Shanghai Hongqiao",
		city: "Shanghai",
		country: "China",
		lat: 31.1979,
		lon: 121.3363,
	},
	{
		code: "URC",
		name: "Urumqi Diwopu",
		city: "Urumqi",
		country: "China",
		lat: 43.9071,
		lon: 87.4742,
	},
	{
		code: "WNZ",
		name: "Wenzhou Longwan",
		city: "Wenzhou",
		country: "China",
		lat: 27.9122,
		lon: 120.8517,
	},
	{
		code: "WUH",
		name: "Wuhan Tianhe",
		city: "Wuhan",
		country: "China",
		lat: 30.7769,
		lon: 114.2096,
	},
	{
		code: "XIY",
		name: "Xi’an Xianyang",
		city: "Xi’an",
		country: "China",
		lat: 34.4471,
		lon: 108.7516,
	},
	{
		code: "XMN",
		name: "Xiamen Gaoqi",
		city: "Xiamen",
		country: "China",
		lat: 24.544,
		lon: 118.127,
	},
	{
		code: "CGO",
		name: "Zhengzhou Xinzheng",
		city: "Zhengzhou",
		country: "China",
		lat: 34.5197,
		lon: 113.8417,
	},

	// Taiwan, China
	{
		code: "KHH",
		name: "Kaohsiung",
		city: "Kaohsiung",
		country: "Taiwan",
		lat: 22.5771,
		lon: 120.3493,
	},
	{
		code: "TPE",
		name: "Taipei Taoyuan",
		city: "Taipei",
		country: "Taiwan",
		lat: 25.0777,
		lon: 121.232,
	},

	// Africa
	{
		code: "JNB",
		name: "Johannesburg OR Tambo",
		city: "Johannesburg",
		country: "South Africa",
		lat: -26.1337,
		lon: 28.242,
	},

	// Americas
	{
		code: "YVR",
		name: "Vancouver",
		city: "Vancouver",
		country: "Canada",
		lat: 49.195,
		lon: -123.1815,
	},
	{
		code: "YYZ",
		name: "Toronto Pearson",
		city: "Toronto",
		country: "Canada",
		lat: 43.6777,
		lon: -79.6248,
	},
	{
		code: "BOS",
		name: "Boston Logan",
		city: "Boston",
		country: "USA",
		lat: 42.3656,
		lon: -71.0096,
	},
	{
		code: "ORD",
		name: "Chicago O'Hare",
		city: "Chicago",
		country: "USA",
		lat: 41.9742,
		lon: -87.9073,
	},
	{
		code: "DFW",
		name: "Dallas/Fort Worth",
		city: "Dallas–Fort Worth",
		country: "USA",
		lat: 32.8998,
		lon: -97.0403,
	},
	{
		code: "LAX",
		name: "Los Angeles",
		city: "Los Angeles",
		country: "USA",
		lat: 33.9416,
		lon: -118.4085,
	},
	{
		code: "JFK",
		name: "New York JFK",
		city: "New York",
		country: "USA",
		lat: 40.6413,
		lon: -73.7781,
	},
	{
		code: "SFO",
		name: "San Francisco",
		city: "San Francisco",
		country: "USA",
		lat: 37.6213,
		lon: -122.379,
	},

	// Asia
	{
		code: "DAC",
		name: "Dhaka",
		city: "Dhaka",
		country: "Bangladesh",
		lat: 23.8433,
		lon: 90.3978,
	},
	{
		code: "PNH",
		name: "Phnom Penh",
		city: "Phnom Penh",
		country: "Cambodia",
		lat: 11.5466,
		lon: 104.844,
	},
	{
		code: "DEL",
		name: "Delhi",
		city: "Delhi",
		country: "India",
		lat: 28.5562,
		lon: 77.1,
	},
	{
		code: "BOM",
		name: "Mumbai",
		city: "Mumbai",
		country: "India",
		lat: 19.0896,
		lon: 72.8656,
	},
	{
		code: "BLR",
		name: "Bengaluru",
		city: "Bengaluru",
		country: "India",
		lat: 13.1986,
		lon: 77.7066,
	},
	{
		code: "MAA",
		name: "Chennai",
		city: "Chennai",
		country: "India",
		lat: 12.9941,
		lon: 80.1709,
	},
	{
		code: "HYD",
		name: "Hyderabad",
		city: "Hyderabad",
		country: "India",
		lat: 17.24,
		lon: 78.4281,
	},
	{
		code: "DPS",
		name: "Denpasar Bali",
		city: "Denpasar",
		country: "Indonesia",
		lat: -8.7482,
		lon: 115.1675,
	},
	{
		code: "CGK",
		name: "Jakarta",
		city: "Jakarta",
		country: "Indonesia",
		lat: -6.1256,
		lon: 106.6559,
	},
	{
		code: "SUB",
		name: "Surabaya",
		city: "Surabaya",
		country: "Indonesia",
		lat: -7.379,
		lon: 112.787,
	},
	{
		code: "FUK",
		name: "Fukuoka",
		city: "Fukuoka",
		country: "Japan",
		lat: 33.5859,
		lon: 130.4507,
	},
	{
		code: "NGO",
		name: "Nagoya Chubu",
		city: "Nagoya",
		country: "Japan",
		lat: 34.8584,
		lon: 136.8044,
	},
	{
		code: "KIX",
		name: "Osaka Kansai",
		city: "Osaka",
		country: "Japan",
		lat: 34.4347,
		lon: 135.2442,
	},
	{
		code: "CTS",
		name: "Sapporo New Chitose",
		city: "Sapporo",
		country: "Japan",
		lat: 42.7752,
		lon: 141.6923,
	},
	{
		code: "HND",
		name: "Tokyo Haneda",
		city: "Tokyo",
		country: "Japan",
		lat: 35.5494,
		lon: 139.7798,
	},
	{
		code: "NRT",
		name: "Tokyo Narita",
		city: "Tokyo",
		country: "Japan",
		lat: 35.7719,
		lon: 140.3929,
	},
	{
		code: "CEB",
		name: "Cebu",
		city: "Cebu",
		country: "Philippines",
		lat: 10.3093,
		lon: 123.9793,
	},
	{
		code: "MNL",
		name: "Manila",
		city: "Manila",
		country: "Philippines",
		lat: 14.5086,
		lon: 121.0198,
	},
	{
		code: "SGN",
		name: "Ho Chi Minh City",
		city: "Ho Chi Minh City",
		country: "Vietnam",
		lat: 10.8188,
		lon: 106.6518,
	},
	{
		code: "HAN",
		name: "Hanoi",
		city: "Hanoi",
		country: "Vietnam",
		lat: 21.2212,
		lon: 105.8072,
	},
	{
		code: "ICN",
		name: "Seoul Incheon",
		city: "Seoul",
		country: "South Korea",
		lat: 37.4602,
		lon: 126.4407,
	},
	{
		code: "KUL",
		name: "Kuala Lumpur",
		city: "Kuala Lumpur",
		country: "Malaysia",
		lat: 2.7456,
		lon: 101.7099,
	},
	{
		code: "PEN",
		name: "Penang",
		city: "George Town",
		country: "Malaysia",
		lat: 5.2971,
		lon: 100.2746,
	},
	{
		code: "SIN",
		name: "Singapore Changi",
		city: "Singapore",
		country: "Singapore",
		lat: 1.3644,
		lon: 103.9915,
	},
	{
		code: "CMB",
		name: "Colombo",
		city: "Colombo",
		country: "Sri Lanka",
		lat: 7.1808,
		lon: 79.8841,
	},
	{
		code: "BKK",
		name: "Bangkok Suvarnabhumi",
		city: "Bangkok",
		country: "Thailand",
		lat: 13.69,
		lon: 100.7501,
	},
	{
		code: "HKT",
		name: "Phuket",
		city: "Phuket",
		country: "Thailand",
		lat: 8.1111,
		lon: 98.3061,
	},
	{
		code: "KTM",
		name: "Kathmandu",
		city: "Kathmandu",
		country: "Nepal",
		lat: 27.6966,
		lon: 85.3591,
	},

	// Australasia
	{
		code: "BNE",
		name: "Brisbane",
		city: "Brisbane",
		country: "Australia",
		lat: -27.3842,
		lon: 153.1175,
	},
	{
		code: "MEL",
		name: "Melbourne",
		city: "Melbourne",
		country: "Australia",
		lat: -37.669,
		lon: 144.841,
	},
	{
		code: "PER",
		name: "Perth",
		city: "Perth",
		country: "Australia",
		lat: -31.9403,
		lon: 115.9672,
	},
	{
		code: "SYD",
		name: "Sydney",
		city: "Sydney",
		country: "Australia",
		lat: -33.9399,
		lon: 151.1753,
	},
	{
		code: "CNS",
		name: "Cairns",
		city: "Cairns",
		country: "Australia",
		lat: -16.8765,
		lon: 145.7553,
	},
	{
		code: "AKL",
		name: "Auckland",
		city: "Auckland",
		country: "New Zealand",
		lat: -37.0082,
		lon: 174.785,
	},
	{
		code: "CHC",
		name: "Christchurch",
		city: "Christchurch",
		country: "New Zealand",
		lat: -43.4894,
		lon: 172.5322,
	},

	// Europe
	{
		code: "BRU",
		name: "Brussels",
		city: "Brussels",
		country: "Belgium",
		lat: 50.901,
		lon: 4.484,
	},
	{
		code: "CDG",
		name: "Paris CDG",
		city: "Paris",
		country: "France",
		lat: 49.0097,
		lon: 2.5479,
	},
	{
		code: "FRA",
		name: "Frankfurt",
		city: "Frankfurt",
		country: "Germany",
		lat: 50.0379,
		lon: 8.5622,
	},
	{
		code: "MUC",
		name: "Munich",
		city: "Munich",
		country: "Germany",
		lat: 48.3538,
		lon: 11.7861,
	},
	{
		code: "FCO",
		name: "Rome Fiumicino",
		city: "Rome",
		country: "Italy",
		lat: 41.8003,
		lon: 12.2389,
	},
	{
		code: "MXP",
		name: "Milan Malpensa",
		city: "Milan",
		country: "Italy",
		lat: 45.6306,
		lon: 8.7281,
	},
	{
		code: "AMS",
		name: "Amsterdam",
		city: "Amsterdam",
		country: "Netherlands",
		lat: 52.3105,
		lon: 4.7683,
	},
	{
		code: "BCN",
		name: "Barcelona",
		city: "Barcelona",
		country: "Spain",
		lat: 41.2974,
		lon: 2.0833,
	},
	{
		code: "MAD",
		name: "Madrid",
		city: "Madrid",
		country: "Spain",
		lat: 40.4983,
		lon: -3.5676,
	},
	{
		code: "ZRH",
		name: "Zurich",
		city: "Zurich",
		country: "Switzerland",
		lat: 47.4581,
		lon: 8.5555,
	},
	{
		code: "LHR",
		name: "London Heathrow",
		city: "London",
		country: "United Kingdom",
		lat: 51.4706,
		lon: -0.4619,
	},
	{
		code: "MAN",
		name: "Manchester",
		city: "Manchester",
		country: "United Kingdom",
		lat: 53.365,
		lon: -2.272,
	},

	// Middle East
	// {
	// 	code: "TLV",
	// 	name: "Tel Aviv",
	// 	city: "Tel Aviv",
	// 	country: "Israel",
	// 	lat: 32.0005,
	// 	lon: 34.8707,
	// },
	{
		code: "RUH",
		name: "Riyadh",
		city: "Riyadh",
		country: "Saudi Arabia",
		lat: 24.9576,
		lon: 46.6988,
	},
	{
		code: "DXB",
		name: "Dubai",
		city: "Dubai",
		country: "UAE",
		lat: 25.2532,
		lon: 55.3657,
	},
];
